web:
    enable: true
    listen-addr: ":8080"

generic:
    timezone: "Local"
    interval: "15m"

logging:
    threshold: "info"
    verbose: 3

scanner:
    - namespace:
        - "development"
      default:
        schedule:
          - "Mon-Fri  8:00 replicas=1"
          - "Mon-Fri 18:00 replicas=0"
      deployment:
        - selector:
            - "app=shell"
            - "app=nightshift"
          schedule:
          - ""
