web:
    enable: true
    listen-addr: ":8080"

generic:
    timezone: "Europe/Amsterdam"

logging:
    threshold: "info"
    verbose: 3

scanner:
    - namespace:
        - "development-1"
        - "development-2"
        - "development-3"
      default:
        id: default-dev ## optional id, if set, the replica metric is available
        schedule:
          - "Mon-Fri  8:00 replicas=1 state=restore"
          - "Mon-Fri 18:00 replicas=0 state=save"
      deployment:
        - id: shell-dev ## optional id, if set, the replica metric is available
          selector:
            - "app=shell"
            - "app=nightshift"
          schedule:
            - ""

    - namespace:
        - "development-1"
        - "development-2"
        - "development-3"
      type: "statefulset"
      default:
        schedule:
          - "Mon-Fri  8:00 replicas=3 state=restore"
          - "Mon-Fri 18:00 replicas=0 state=save"

    - namespace:
        - "staging"
      default:
        schedule:
          - "Mon-Fri  8:00 replicas=5"
          - "Mon-Fri 18:00 replicas=2"
      deployment:
        - selector:
            - "app=analytics"
          schedule:
          - "Mon-Fri  8:00 replicas=2"
          - "Mon-Fri 18:00 replicas=5"
        - selector:
            - "app=nightshift"
          schedule:
            - ""
