web:
    enable: true
    listen-addr: ":8080"

generic:
    timezone: "Europe/Amsterdam"

logging:
    threshold: "info"
    verbose: 3

trigger:
    - id: refreshdb
      type: job
      config:
        name: somejob
    - id: build
      type: webhook
      config:
        url: http://localhost:8080
        timeout: 1s
    - id: upmetric
      type: metric
      config:
        name: nightshift_scaled
        value: 0
    - id: downmetric
      type: metric
      config:
        name: nightshift_scaled
        value: 1

scanner:

    - namespace:
        - "development-1"
        - "development-2"
        - "development-3"
      default:
        schedule:
          - "Mon-Fri  8:00 replicas=1 state=restore trigger=upmetric,refreshdb,somejob"
          - "Mon-Fri 18:00 replicas=0 state=save trigger=downmetric"
      deployment:
        - selector:
            - "app=shell"
            - "app=nightshift"
          schedule:
            - ""

    - namespace:
        - "development-1"
        - "development-2"
        - "development-3"
      type: "statefulset"
      default:
        schedule:
          - "Mon-Fri  8:00 replicas=3 state=restore"
          - "Mon-Fri 18:00 replicas=0 state=save"

    - namespace:
        - "staging"
      default:
        schedule:
          - "Mon-Fri  8:00 replicas=5"
          - "Mon-Fri 18:00 replicas=2"
      deployment:
        - selector:
            - "app=analytics"
          schedule:
          - "Mon-Fri  8:00 replicas=2"
          - "Mon-Fri 18:00 replicas=5"
        - selector:
            - "app=nightshift"
          schedule:
            - ""
