---
apiVersion: v1
kind: Template
labels:
  template: nightshift
objects:

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: "${SERVICE_ACCOUNT}"
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"${NAME}"}}'

- apiVersion: v1
  kind: Route
  metadata:
    name: "${NAME}"
  spec:
    to:
      kind: Service
      name: "${NAME}"
    tls:
      termination: Reencrypt

- apiVersion: v1
  kind: Service
  metadata:
    name: "${NAME}"
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: "${NAME}-proxy-tls"
      prometheus.io/scrape: "true"
  spec:
    ports:
    - name: auth-proxy
      port: 443
      targetPort: 8443
    selector:
      name: "${NAME}"

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${NAME}"
    annotations:
      joyrex2001.com/nightshift.ignore: "true"
    labels:
      app: "${NAME}"
  selector:
    name: "${NAME}"
  spec:
    selector:
      name: "${NAME}"
    ImagePullPolicy: Always
    replicas: 1
    strategy:
      type: "Recreate"
    template:
      metadata:
        labels:
          name: "${NAME}"
        name: "${NAME}"
      spec:
        serviceAccount: "${SERVICE_ACCOUNT}"
        containers:

          - name: oauth-proxy
            image: openshift/oauth-proxy:latest
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 8443
                name: auth-proxy
            args:
              - --https-address=:8443
              - --provider=openshift
              - --openshift-service-account=${SERVICE_ACCOUNT}
              - --upstream=http://localhost:8080
              - --tls-cert=/etc/tls/private/tls.crt
              - --tls-key=/etc/tls/private/tls.key
              - --openshift-sar={"namespace":"$(MY_POD_NAMESPACE)","resource":"services","name":"${NAME}","verb":"update"}
              - --cookie-secret=${COOKIE_SECRET}
            env:
              - name: MY_POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
            resources:
              limits:
                memory: "64Mi"
            volumeMounts:
              - mountPath: /etc/tls/private
                name: proxy-tls

          - name: ${NAME}
            image: "${NIGHTSHIFT_IMAGE}"
            args:
              - --config=/etc/nightshift/config.yaml
              - --enable-web=true
            readinessProbe:
              httpGet:
                path: "/healthz"
                port: 8080
              initialDelaySeconds: 3
              timeoutSeconds: 3
            livenessProbe:
              httpGet:
                path: "/healthz"
                port: 8080
              initialDelaySeconds: 5
              timeoutSeconds: 3
            resources:
              limits:
                memory: "64Mi"
              requests:
                cpu: "0.1"
            volumeMounts:
              - mountPath: /etc/nightshift/
                name: config-volume

        volumes:
          - name: config-volume
            configMap:
              name: ${NIGHTSHIFT_CONFIGMAP}
          - name: proxy-tls
            secret:
              secretName: "${NAME}-proxy-tls"

parameters:
- name: NAME
  description: |-
    The name assigned to all of the objects defined in this template.
  displayName: Name
  required: true
  value: nightshift

- name: NIGHTSHIFT_IMAGE
  description: |-
    The container image to be used for running this service.
  displayName: Container image.
  required: true
  value: "docker.io/joyrex2001/nightshift:latest"

- name: NIGHTSHIFT_CONFIGMAP
  description: |-
    The name of the configmap that contains the config.yaml configuration file.
  displayName: Nightshift configmap name.
  required: true
  value: "nightshift-config"

- name: SERVICE_ACCOUNT
  displayName: Service account
  description: |-
    Service account to be used when running this service. This service service
    should have read and write permissions on the projects it should be able
    to scale.
  required: false
  value: "nightshift"

- name: COOKIE_SECRET
  description: cookie secret for oauth-proxy
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  required: true
